// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3ChMswZ9rBP0Cs3lslA--NptnEhhOSo',
    appId: '1:1062526358504:web:b568a359de65afdfaa4a5d',
    messagingSenderId: '1062526358504',
    projectId: 'flutter-first-a21a1',
    authDomain: 'flutter-first-a21a1.firebaseapp.com',
    storageBucket: 'flutter-first-a21a1.appspot.com',
    measurementId: 'G-QQFVELHCDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6jb-He4lF3EbgNPixohGpcS5aNV2XcZg',
    appId: '1:1062526358504:android:28523d69ee5c7a6aaa4a5d',
    messagingSenderId: '1062526358504',
    projectId: 'flutter-first-a21a1',
    storageBucket: 'flutter-first-a21a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDnQ04x-f0RQYyF1U3Bim3V3FJdozINrM',
    appId: '1:1062526358504:ios:60dae98d247fb6efaa4a5d',
    messagingSenderId: '1062526358504',
    projectId: 'flutter-first-a21a1',
    storageBucket: 'flutter-first-a21a1.appspot.com',
    iosBundleId: 'com.example.page',
  );
}
